### PR TITLE
Add party links to person pages

### PR DESCRIPTION
**Pull request by tfgg**
image
image

### CODE REVIEW

**Comment by andylolz** [comment]
Where there’s no party emblem, I wonder if we can leave a little padding between candidate links and party links?

Alternatively, we could add headings above the two sets of links?

**Comment by tfgg** [comment]
Sounds like a good idea. I'll have a go.

**Comment by tfgg** [comment]
image

**Comment by tfgg** [comment]
Fixed possessive:
image

**Comment by andylolz** [comment]
looks good!

**Pull request merged**
