### PR TITLE
Port metadata from edit site

### PR DESCRIPTION
**Pull request by tfgg**
Addresses Issue #55

### CODE REVIEW

**Comment by tfgg** [comment]
TODO:
- Generate person descriptions in the same way as https://github.com/mysociety/yournextmp-popit/blob/master/candidates/templatetags/metadescription.py, this may be the time for me to learn ruby.
- Test!

**Comment by tfgg** [comment]
So this seems to be more or less working for FB

image
image

As you can see, missing images show up as white because the blank man/woman images are white on transparent pngs. The links to those could be replaced to fix that issue.

Currently I can't get the Twitter card validator (https://cards-dev.twitter.com/validator) to read from my staging site, so I have no idea how well they display there.

Parties starting with "The" are handled but parties that don't end in "Party" are handled inconsistently grammar-wise

image
image

simply appending "party" would mess up common cases, e.g. "Liberal Democrats".

**Comment by tfgg** [comment]
This is now more like the yournextmp-popit repo and uses the imageproxy. However, the Facbeook images now seem lower quality and blockier (due to being resized to 80x80). Making them larger (~200x200 recommended by docs) seems to cause problems with image colours.

**Comment by symroe** [comment]
LGTM

**Pull request merged**
