### PR TITLE
Add requirements.txt for Python requirements

### PR DESCRIPTION
**Pull request by zarino**
I noticed `_scripts/build_constituency_centres.py` requires the Requests library, so rather than just installing it, I created a requirements.txt for other people to run too.

### CODE REVIEW

**Comment by symroe** [comment]
There's actually a requirements file already at https://github.com/DemocracyClub/YourNextMP-Read/blob/master/_scripts/flask/requirements.txt, but it's really not obvious.  Maybe one at the root should just import that one?

**Comment by andylolz** [comment]
This lgtm.

> Maybe one at the root should just import that one?

Or the other way around? The flask one has a load of flask stuff that isn’t needed for just building and running locally with `jekyll serve`.

**Comment by zarino** [comment]
Yeah – what @andylolz said.

**Comment by symroe** [comment]
Fair enough! :)

**Pull request merged**
