### PR TITLE
Bugfix for candidates who just have year in field

### PR DESCRIPTION
**Pull request by jarofgreen**
My build was crashing here with a ValueError

### CODE REVIEW

**Comment by andylolz** [comment]
This will show:

> Age: Unknown

…when there’s just a birth year. Would be good to instead show e.g.:

> Age: 54 or 55

…the way YNMP-edit currently does.

Although not crashing is preferable to crashing :P

**Comment by jarofgreen** [comment]
It would be good to show that. Let's start with it just not crashing tho, then look at showing a proper age thing later.

**Comment by jarofgreen** [comment]
Apparently @andylolz is working on better fix that shows approx range, so closing this unmerged

**Comment by symroe** [comment]
Thanks both!

**Pull request merged**
