### PR TITLE
Filter out events further away than 3 times the size of the constituency bounds

### PR DESCRIPTION
**Pull request by symroe**
Get the size of the constituency from MaPit, then times it by 3 and use that as a rough filter for events to show on a constituency.

### CODE REVIEW

**Comment by jarofgreen** [comment]
`if 'venue' in event and 'lat' in event['venue']:
            if not event['venue']['lat']:
 continue`

If I understand this correctly, any event with a venue but where the venue does not have a lat will not be shown?  I am completely against this - this will exclude to much good data

**Comment by symroe** [comment]
Oh, whoops, got the logic backwards

**Comment by jarofgreen** [comment]
Also, you need to increase 40 miles massively. In rural areas that will cut out far to much. I'd even say 200 or 300 miles - this is only meant to catch the really crazy cases, London to Birmingham

**Comment by jarofgreen** [comment]
> if not mapit_centres.get(constituency_id): continue 

This should never happen right? They should all be there? Could this default to include then so a random error later doesn't remove all events?

**Comment by jarofgreen** [comment]
Huh, London to Birmingham is 120 miles. However, I really want this high so as to exclude false removals. Maybe 100 miles then, but I will still be watching that in rural areas and adjusting later.

**Comment by symroe** [comment]
The distance currently removes 2 events, both manually tested to ensure they aren't relevant.  Can make it a bit higher, but really 40 miles is a long way to travel for an event anyway.

PR updated to only filter events with a known location that is over the distance.

As for the `constituency_id` not being in `mapit_centres` – MaPit doesn't have Northern Ireland shapes, so it will happen every time in NI.

**Comment by jarofgreen** [comment]
> but really 40 miles is a long way to travel for an event anyway.

It's not in the highlands. That's a London perspective. It must be higher.

**Comment by jarofgreen** [comment]
Sorry to be a pain about this, but 60 miles is still to small.

The distance between Orkney and Shetland is 120 miles, and that's one seat.

**Comment by jarofgreen** [comment]
Edit: 100 miles, by other look up. Still tho, sorry.

**Comment by jarofgreen** [comment]
If it's left at 60 for now, can it log any it excludes so I can check them and raise the limit if needed?

**Comment by symroe** [comment]
@jarofgreen are you happy with this?

**Comment by jarofgreen** [comment]
My python's a bit rusty but is_in_area will return true if no venue or no lat right?

Then yes

**Comment by symroe** [comment]
Yep

**Pull request merged**
