### PR TITLE
Elected banner

### PR DESCRIPTION
**Pull request by symroe**
Adds a banner to the person page if `page.person.candidacies.ge2015.constituency.elected` is `True`.

To test this you'll need to run:

`_scripts/build.sh staging` before running Jekyll as normal.

### CODE REVIEW

**Comment by zarino** [comment]
I've just pushed some styling for these banners. They look like:

winner-constituency

winner

loser

As you can tell from the second screenshot (Blue rosette?? Labour??), I’ve had trouble converting the party ID into a slug suitable for a rosette image filename. I imagine there are also cases where we'll want multiple "parties" to be covered by the same rosette (eg: "Labour and Cooperative" candidates who really shouldn't be left with the generic grey rosette). So a developer could do with looking at that and picking something sensible.

Also, I wasn't sure [where to link to](https://github.com/DemocracyClub/YourNextMP-Read/blob/4d369a37a09ef6ca575c9fa48fd2a6d8e99d8b30/_includes/constituency_winner.html#L30-L35) in the case that the winning candidate has no PublicWhip ID. Ideas @mhl @symroe?

**Comment by symroe** [comment]
Where to link to might be a question for @dracos too

**Comment by symroe** [comment]
The only thing left to do on this is figure out where to link to when we don't have a publicwhip ID.

**Comment by dracos** [comment]
I don't know the details of how this site is working, but can you have a script that finds out the new ID (querying the TWFY API, perhaps) and adds that to the data source you're using? I realise that's quite a circle, with YNMP updating, parlparse fetching and potentially creating a new entry, and then this pulling it back to get the new ID, but it might work? As a last resort, you can link to the search page for their name which should then show the person and link to them, but that wouldn't work for a direct alert signup link.

**Comment by symroe** [comment]
Let's link to the search page for now – the other option sounds too complex to get done in a reliable way at this stage.

**Comment by tfgg** [comment]
This seems to be building fine and displaying properly right now.

**Comment by mhl** [comment]
If someone would like to review https://github.com/mysociety/yournextmp-popit/pull/368 we can get the parlparse IDs for new people back from TheyWorkForYou, as @dracos suggested above.

**Pull request merged**
