### PR TITLE
Home page

### PR DESCRIPTION
**Pull request by symroe**
An initial attempt at the new home page

screen shot 2015-04-16 at 16 26 01

### CODE REVIEW

**Comment by symroe** [comment]
screen_shot_2015-04-16_at_16_26_01

**Comment by tfgg** [comment]
Looks good for now.

Maybe remove the em in "Get to know the candidates in your constituency" since "your" is already emphasized in the header above.

The ugly bar could be fixed by introducing some sort of "check out this random candidate" feature at a later point :)

Are we only including Democracy Club data? Though I agree it's good to promote DC on the front page explicitly.

**Comment by symroe** [comment]
- Removed the `em`
- Ugly bar ok for the time being
- Text: Yes, it's only DC data at the moment

**Comment by tfgg** [comment]
:+1: sounds good!

**Comment by JoeMitchell** [comment]
Exciting!

If I was being picky (and trying to predict what userresearch28292 might say)... Is it obvious (enough) that this is about the election? Does userresearcher82827 know what a ballot paper is? 

How about "Who can you vote for on Thursday 7 May?" or 'in the General Election?' 

As for the 'bit naff' text - I think it's fine, but maybe we should assume that people don't know what DC is, so:

"YourNextMP.com brings together data that a team of volunteers has collated over the last six months. It aims to give you a complete picture of your candidates."

**Pull request merged**
