### PR TITLE
Tidy up _data_small build process

### PR DESCRIPTION
**Pull request by tfgg**
This should stop _data_small files being shown in `git status`.

### CODE REVIEW

**Comment by andylolz** [comment]
```
$ _scripts/build.sh 

Traceback (most recent call last):
  File "_scripts/build_data_small.py", line 17, in <module>
    "_data_small/{0}".format(constituency_filename),
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 2] No such file or directory: '_data_small/constituencies/id/65913.json'
```

Oh right, I see – it’s becuase the _data_small/constituencies/id/ directory doesn’t exist.

Should possibly combine with #103 (or merge that first).

**Comment by andylolz** [comment]
Oh right, I see – it’s becuase the _data_small/constituencies/id/ directory doesn’t exist.

Should possibly combine with #103.

**Comment by tfgg** [comment]
#103 now seems ok, so this can be merged I think.

**Comment by andylolz** [comment]
looks good, yeah!

**Pull request merged**
